      SUBROUTINE ARINI
c.....before invoking ARINI:
c.....IAPAR2(1), IAINT2(1) must be set.
      COMMON /ARPRNT/ ARPAR1(100), IAPAR2(50), ARINT1(100), IAINT2(50)
cc      SAVE /ARPRNT/
      SAVE   
ctest off for resonance (phi, K*) studies:
c      OPEN (89, FILE = 'ana/decay_rec.dat', STATUS = 'UNKNOWN')
      IFLG = IAPAR2(1)
      GOTO (200, 200, 300) IFLG
c.....error choice of initialization
      PRINT *, 'IAPAR2(1) must be 1, 2, or 3'
      STOP
c.....to use default initial conditions generated by the cascade,
c.....or to read in initial conditions.
 200  RETURN
c.....to generate formation time and the position at formation time from 
c.....read-in initial conditions with an averaged formation proper time.
 300  CALL ARINI1
c.....ordering the particle label according to increasing order of 
c.....formation time.
      CALL ARTORD
      RETURN
      END
c-----------------------------------------------------------------------
c.....subroutine to generate formation time and position at formation time
c.....from read-in initial conditions with an averaged formation proper 
c.....time.
